"""Pydantic schemas"""
from app.api.v1.schemas.user import (
    UserRegister,
    UserLogin,
    Token,
    UserResponse,
    LoginResponse,
    ChangePassword,
    UpdateProfile,
)
from app.api.v1.schemas.note import (
    NoteCreate,
    NoteUpdate,
    NoteListItem,
    NoteResponse,
    NoteContentResponse,
    NoteListResponse,
    PaginationMeta,
)
from app.api.v1.schemas.notebook import (
    NotebookCreate,
    NotebookUpdate,
    NotebookResponse,
    NotebookListResponse,
)
from app.api.v1.schemas.ai import (
    ChatMessage,
    ChatRequest,
    ChatResponse,
    ExploreRequest,
    ExploreResponse,
    ExtractPointRequest,
    ExtractPointResponse,
    GenerateMindmapRequest,
    GenerateMindmapResponse,
    MindmapNode,
    CheckSummaryRequest,
    CheckSummaryResponse,
)
from app.api.v1.schemas.conversation import (
    QAPairCreate,
    QAPairResponse,
    ConversationSaveRequest,
    ConversationResponse,
    ConversationListItem,
    ConversationListResponse,
)

__all__ = [
    "UserRegister",
    "UserLogin",
    "Token",
    "UserResponse",
    "LoginResponse",
    "ChangePassword",
    "UpdateProfile",
    "NoteCreate",
    "NoteUpdate",
    "NoteListItem",
    "NoteResponse",
    "NoteContentResponse",
    "NoteListResponse",
    "PaginationMeta",
    "NotebookCreate",
    "NotebookUpdate",
    "NotebookResponse",
    "NotebookListResponse",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "ExploreRequest",
    "ExploreResponse",
    "ExtractPointRequest",
    "ExtractPointResponse",
    "GenerateMindmapRequest",
    "GenerateMindmapResponse",
    "MindmapNode",
    "CheckSummaryRequest",
    "CheckSummaryResponse",
    "QAPairCreate",
    "QAPairResponse",
    "ConversationSaveRequest",
    "ConversationResponse",
    "ConversationListItem",
    "ConversationListResponse",
]
